name: animal_trivia
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^1.1.0
  dartz: ^0.10.1
  json_annotation: ^4.4.0
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  mocktail: ^0.0.1-dev.12
  http_mock_adapter: ^0.3.2

flutter:

  uses-material-design: true
