name: animal_trivia
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.4
  freezed_annotation: ^1.1.0
  dartz: ^0.10.1
  json_annotation: ^4.4.0
  dio: ^4.0.4
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  injectable: ^1.5.0
  auto_localization: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  freezed: ^1.1.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  http_mock_adapter: ^0.3.2
  mockito: ^5.0.17
  injectable_generator: ^1.5.2
  network_image_mock: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
  
