# This is a basic workflow to help you get started with Actions
name: animal_trivia

on:
  push:
    paths:
      - "lib/**"
      - "test/**"
      - "pubspec.*"
      - ".github/workflows/main.yml"

  pull_request:
    paths:
      - "lib/**"
      - "test/**"
      - "pubspec.*"
      - ".github/workflows/main.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: subosito/flutter-action@v1.5.3
      
      - name: Install Dependencies
        run: flutter packages get
      
      - name: Format
        run: flutter format --set-exit-if-changed lib test
      
      - name: Analyze
        run: flutter analyze lib test
        
      - name: Buidl Runner
        run:  flutter pub run build_runner build --delete-conflicting-outputs
      
      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
      
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          min_coverage: 80
